# automatically generated by the FlatBuffers compiler, do not modify

# namespace: classes

import flatbuffers

class AndroidImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAndroidImage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AndroidImage()
        x.Init(buf, n + offset)
        return x

    # AndroidImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AndroidImage
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AndroidImage
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AndroidImage
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AndroidImage
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # AndroidImage
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # AndroidImage
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def AndroidImageStart(builder): builder.StartObject(4)
def AndroidImageAddHeight(builder, height): builder.PrependInt32Slot(0, height, 0)
def AndroidImageAddWidth(builder, width): builder.PrependInt32Slot(1, width, 0)
def AndroidImageAddFormat(builder, format): builder.PrependInt32Slot(2, format, 0)
def AndroidImageAddData(builder, data): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AndroidImageStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def AndroidImageEnd(builder): return builder.EndObject()
