// automatically generated by the FlatBuffers compiler, do not modify

package io.jeti.measure.utils;

import java.nio.*;
import java.lang.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Capture extends Table {
  public static Capture getRootAsCapture(ByteBuffer _bb) { return getRootAsCapture(_bb, new Capture()); }
  public static Capture getRootAsCapture(ByteBuffer _bb, Capture obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Capture __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startCapture(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endCapture(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishCaptureBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

